######################################################################
# Automatically generated by qmake (2.00a) Tue Jul 19 09:53:21 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h ../ecomm.h
FORMS += test-search.ui
SOURCES += main.cpp ../ecomm.cpp
